# Generated by Django 5.1.7 on 2025-03-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0004_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delete',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='insert',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='update',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
