# Generated by Django 5.1.7 on 2025-03-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0005_alter_delete_email_alter_insert_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='password',
        ),
    ]
