# Generated by Django 5.1.7 on 2025-03-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0006_remove_update_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='insert',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='insert',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
