# Generated by Django 5.1.7 on 2025-03-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0007_insert_is_admin_insert_is_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insert',
            name='confirmpassword',
        ),
        migrations.AlterField(
            model_name='insert',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='insert',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
