# Generated by Django 5.1.7 on 2025-03-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0008_remove_insert_confirmpassword_alter_insert_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insert',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='insert',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
